### ISSUE TITLE
Need documentation and licence to contribute

### ISSUE THREAD

**Issue by riggedCoinflip** [barrysheppard/killteam-card-creator#1]
**From the existing card creators, I like the style of this one the best as it allows me to generate playing-card-size data cards from the generated images.**

## I would like to add some features to fix issues I had using the card creator, which could include
- Add another weapon (some operatives wave weapon modes for example so I would need 2 ranged + 1 melee weapon)
- Add coloured geometry icons (currently for "Range ⬟" there is only black/white unicode) - perhaps even add the inches inside like Wahapedia does)
- Add multiple operatives
- Add operatives from Battlescribe Rosters (.rosz)
- Create a printable PDF of the operatives in playing card format
- Add the option to add rulecards

**My vision is to make this project like Datacard App, but with more customization options and printable to playing card format**

# To do that, I need
- An update to the readme which includes steps on how to run it locally (you seem to use some template language for example, but no documentation for it)
- A permissive LICENCE (licence.md) so I am actually allowed to do anything for the project.

Thank you!

**Comment by barrysheppard** [comment]
README.md updated to include how to run and license. This was based on the Warcry Card Creator project which was Creative Commons 4.0 I had it listed in the instructions tab but it should have at least been in the README as well.

Hopefully that's everything you need! Have fun!
